INSERT INTO EVENT (EVENT_TITLE, EVENT_DATE, EVENT_PLACE) VALUES ('Jazz concert', '2022-02-01', 'London');
INSERT INTO EVENT (EVENT_TITLE, EVENT_DATE, EVENT_PLACE) VALUES ('Rock concert', '2022-03-01', 'Budapest');
INSERT INTO EVENT (EVENT_TITLE, EVENT_DATE, EVENT_PLACE) VALUES ('Hard Rock concert', '2022-01-01', 'Paris');


INSERT INTO USERBOOKING (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS) VALUES('Adams', 'Roy', 'radams1v@xinhuanet.com');
INSERT INTO USERBOOKING (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS) VALUES('Adams', 'Martin', 'madams2b@msu.edu');
INSERT INTO USERBOOKING (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS) VALUES('Alvarez', 'Roger', 'ralvarezk@blogs.com');

INSERT INTO TICKET (USER_ID, EVENT_ID, CATEGORY) VALUES ((SELECT USER_ID FROM USERBOOKING WHERE EMAIL_ADDRESS = 'ralvarezk@blogs.com'), (SELECT EVENT_ID FROM EVENT WHERE EVENT_PLACE = 'Budapest'), 'STANDARD');

