CREATE TABLE EVENT(
  EVENT_ID BIGSERIAL PRIMARY KEY,
  EVENT_TITLE VARCHAR(64) NOT NULL,
  EVENT_DATE DATE,
  EVENT_PLACE VARCHAR(64)
);

CREATE TABLE USERBOOKING(
  USER_ID BIGSERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64)
);

CREATE TABLE TICKET(
  TICKET_ID BIGSERIAL PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  EVENT_ID BIGINT NOT NULL,
  CATEGORY VARCHAR(64)
);

ALTER TABLE TICKET ADD FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID);
ALTER TABLE TICKET ADD FOREIGN KEY (USER_ID) REFERENCES USERBOOKING(USER_ID);
CREATE INDEX IDX_CATEGORY_ ON TICKET(CATEGORY);
